/*
 * This source file was generated by the Gradle 'init' task
 */

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;

class AppTest {
    @Test
    void sanityCheck() {
        assertTrue(true);
    }
}
